language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE laramentor;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit